# Generated by Django 3.1.5 on 2021-01-27 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя категории')),
                ('slug', models.SlugField(max_length=30)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип')),
                ('logo_ico', models.ImageField(upload_to='logo/ico/', verbose_name='Логотип ico')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Фото блог',
                'verbose_name_plural': 'Фото блоги',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_blog_constructor.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=10000000, verbose_name='Описание')),
                ('photo', models.FileField(upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИ')),
                ('client', models.CharField(max_length=40, verbose_name='Клиент')),
                ('budget', models.CharField(max_length=10, verbose_name='Бюджет')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_blog_constructor.category', verbose_name='Категория')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_blog_constructor.portfolio')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_blog_constructor.portfolio')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_blog_constructor.post')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_blog_constructor.reader')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_blog_constructor.post')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_blog_constructor.reader')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_blog_constructor.portfolio'),
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_blog_constructor.portfolio')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_blog_constructor.reader')),
            ],
        ),
    ]
