# Generated by Django 3.1.5 on 2021-01-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_blog_constructor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='portfolio',
        ),
    ]
