# Generated by Django 3.1.5 on 2021-02-05 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_blog_constructor', '0002_remove_like_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vk', 'Vk'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('dribbble', 'Dribbble'), ('amazon', 'Amazon'), ('github', 'Github'), ('instagram', 'Instagram'), ('skype', 'Skype'), ('youtube-1', 'Youtube')], max_length=15, verbose_name='Имя соцсети')),
                ('link', models.URLField(verbose_name='Ссылка на соцсеть')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_blog_constructor.portfolio')),
            ],
            options={
                'verbose_name': 'Соцсеть',
                'verbose_name_plural': 'Соцсети',
            },
        ),
    ]
